### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wauputra** [gmurdoko/student-code#1]
https://github.com/gmurdoko/student-code/blob/1866f47553b4ea207dd7af4d95e90f5291558546/php-dasar/pertemuan4/function.php#L14

penulisan function tidak disertai dengan echo

`<h1><?= echo salam("Siang","Galang"); ?></h1> `

manjadi

`<h1><?=  salam("Siang","Galang"); ?></h1>`

**Comment by gmurdoko** [comment]
oke terimakasih
